name: CI

on: [push]

jobs:
  
  tag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@master
      
    - uses: actions/setup-dotnet@v1 # Downloads & adds dotnet to PATH
      with:
        dotnet-version: '3.1.100-preview3-014645' # SDK Version to use.
      
    #- name: Git Tag
    #  shell: powershell
    #  run: |
    #    $tag = (Get-Date -Format "dd.MM.yyyy-hh.mm") + "-" + (git log --format=%h -1)
    #    git tag $tag
    #    Write-Host git tag set to $tag
        
    - name: dotnet build SpotifyNet
      shell: powershell
      run: |
        New-Item -ItemType Directory -Path C:\artifacts -Force
        dotnet build .\SpotifyNet\SpotifyNet.csproj -o ../output/SpotifyNet
        Compress-Archive -Path ..\output\SpotifyNet\* -DestinationPath C:\artifacts\SpotifyNet.zip
    
    - name: dotnet build SpotifyNet.Cover
      shell: powershell
      run: |
        New-Item -ItemType Directory -Path C:\artifacts -Force
        dotnet build .\SpotifyNet.Cover\SpotifyNet.Cover.csproj -o ../output/SpotifyNet.Cover
        Compress-Archive -Path ..\output\SpotifyNet.Cover\* -DestinationPath C:\artifacts\SpotifyNet.Cover.zip
        
    - uses: actions/upload-artifact@v1
      with:
        name: SpotifyNet
        path: ..\output\SpotifyNet
      
    - uses: actions/upload-artifact@v1
      with:
        name: SpotifyNet.Cover
        path: ..\output\SpotifyNet.Cover
      
    - name: dotnet pack release
      working-directory: SpotifyNet
      run: dotnet pack -c Release -o ../output
      
    - name: Setup NuGet.exe
      uses: warrenbuckley/Setup-Nuget@v1
    
    - name: Setup NuGet source
      run: nuget sources Add -Name "github" -Source "https://nuget.pkg.github.com/TheBlubb14/index.json" -UserName "TheBlubb14" -Password "${{ secrets.GITHUB_TOKEN }}"
    
    - name: NuGet push
      working-directory: output
      run: nuget push *.nupkg -Source "github" -ApiKey "${{ secrets.GITHUB_TOKEN }}" -SkipDuplicate
     

      
   # Create a new release: create a tag, then 'git push origin <tagname>', wait for it to build
    - name: Create a new GitHub release if a new tag is pushed
      uses: softprops/action-gh-release@v1
      with:
        files: |
          C:\artifacts\SpotifyNet.zip
          C:\artifacts\SpotifyNet.Cover.zip
        #body: |

      #if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
