name: CI

on: [push]

jobs: 
  tag:
    runs-on: ubuntu-latest
    
    outputs:
      version: ${{ steps.tag-action.outputs.new_tag }}
   
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0 # set the fetch-depth for actions/checkout@master to be sure you retrieve all commits to look for the semver commit message.

      - name: Bump version and push tag
        id: tag-action
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: TheBlubb14
    
  build:
    needs: [tag]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
       
      - name: Fetch tags
        run: git fetch origin +refs/tags/*:refs/tags/*

      - name: Display version
        run: echo New version ${{ needs.tag.outputs.version }}

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1 # Downloads & adds dotnet to PATH
        with:
          dotnet-version: '3.1.302' # SDK Version to use.
       
      - name: dotnet build SpotifyNet
        shell: powershell
        run: |
          New-Item -ItemType Directory -Path C:\artifacts -Force
          dotnet build .\SpotifyNet\SpotifyNet.csproj -o ../output/SpotifyNet -p:Version=${{ needs.tag.outputs.version }}
          Compress-Archive -Path ..\output\SpotifyNet\* -DestinationPath C:\artifacts\SpotifyNet.zip
    
      - name: dotnet build SpotifyNet.Cover
        shell: powershell
        run: |
          New-Item -ItemType Directory -Path C:\artifacts -Force
          dotnet build .\SpotifyNet.Cover\SpotifyNet.Cover.csproj -o ../output/SpotifyNet.Cover -p:Version=${{ needs.tag.outputs.version }}
          Compress-Archive -Path ..\output\SpotifyNet.Cover\* -DestinationPath C:\artifacts\SpotifyNet.Cover.zip
       
      - uses: actions/upload-artifact@v1
        with:
          name: SpotifyNet
          path: ..\output\SpotifyNet
     
      - uses: actions/upload-artifact@v1
        with:
          name: SpotifyNet.Cover
          path: ..\output\SpotifyNet.Cover
     
      - name: dotnet pack release
        working-directory: SpotifyNet
        run: dotnet pack -p:PackageVersion=${{ needs.tag.outputs.version }} -c Release -o ../output
     
      - name: Setup NuGet.exe
        uses: warrenbuckley/Setup-Nuget@v1
    
      - name: Setup NuGet source
        run: nuget sources Add -Name "github" -Source "https://nuget.pkg.github.com/TheBlubb14/index.json" -UserName "TheBlubb14" -Password "${{ secrets.GITHUB_TOKEN }}"
    
      - name: NuGet push
        working-directory: output
        run: nuget push *.nupkg -Source "github" -ApiKey "${{ secrets.GITHUB_TOKEN }}" -SkipDuplicate

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
