name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@master
      
    - uses: actions/setup-dotnet@v1 # Downloads & adds dotnet to PATH
      with:
        dotnet-version: '3.0.100-preview8-013656' # SDK Version to use.
      
    - name: dotnet build SpotifyNet
      shell: powershell
      run: |
        New-Item -ItemType Directory -Path C:\artifacts -Force
        dotnet build .\SpotifyNet\SpotifyNet.csproj -o ../output/SpotifyNet
        Compress-Archive -Path ..\output\SpotifyNet\* -DestinationPath C:\artifacts\SpotifyNet.zip
    
    - name: dotnet build SpotifyNet.Cover
      shell: powershell
      run: |
        New-Item -ItemType Directory -Path C:\artifacts -Force
        dotnet build .\SpotifyNet.Cover\SpotifyNet.Cover.csproj -o ../output/SpotifyNet.Cover
        Compress-Archive -Path ..\output\SpotifyNet.Cover\* -DestinationPath C:\artifacts\SpotifyNet.Cover.zip
        
    - uses: actions/upload-artifact@v1
      with:
        name: SpotifyNet
        path: C:\artifacts\SpotifyNet.zip
      
    - uses: actions/upload-artifact@v1
      with:
        name: SpotifyNet.Cover
        path: C:\artifacts\SpotifyNet.Cover.zip
      
    - name: dotnet pack release
      working-directory: SpotifyNet
      run: dotnet pack -c Release -o ../output
      
    - name: Setup NuGet.exe
      uses: warrenbuckley/Setup-Nuget@v1
    
    - name: Setup NuGet source
      run: nuget sources Add -Name "github" -Source "https://nuget.pkg.github.com/TheBlubb14/index.json" -UserName "TheBlubb14" -Password "${{ secrets.GITHUB_TOKEN }}"
    
    - name: NuGet push
      working-directory: output
      run: nuget push *.nupkg -Source "github" -ApiKey "${{ secrets.GITHUB_TOKEN }}" -SkipDuplicate
